name: $(GITVERSION_SemVer)

pool: Default

pr: none
trigger:
  - master
  - develop

jobs:
- template: version.yml

- ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
  - deployment: Production
    displayName: Production Deployment
    environment: Production
    dependsOn: SetupVersioning
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          # - template: package.yml
          #   parameters:
          #     platform: Win64
          #     engineVersion: '4.26'
          #     releaseVersion: $(Build.BuildNumber)
          - template: package.yml
            parameters:
              platform: Win64
              engineVersion: '4.27'
              releaseVersion: $(Build.BuildNumber)
          - task: GitHubRelease@1
            displayName: 'Create GitHub Release'
            inputs:
              gitHubConnection: 'GitHub Connection'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: v$(Build.BuildNumber)
              title: $(Build.BuildNumber)
              assets: '$(System.DefaultWorkingDirectory)/output/*.zip'
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'
- ${{ else }}:
  - deployment: NonProduction
    displayName: Non-Production Deployment
    environment: Non-Production
    dependsOn: SetupVersioning
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          # - template: package.yml
          #   parameters:
          #     platform: Win64
          #     engineVersion: '4.26'
          #     releaseVersion: $(Build.BuildNumber)
          - template: package.yml
            parameters:
              platform: Win64
              engineVersion: '4.27'
              releaseVersion: $(Build.BuildNumber)
          - task: GitHubRelease@1
            displayName: 'Create GitHub Release'
            inputs:
              gitHubConnection: 'GitHub Connection'
              repositoryName: '$(Build.Repository.Name)'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'userSpecifiedTag'
              tag: v$(Build.BuildNumber)
              title: $(Build.BuildNumber)
              assets: '$(System.DefaultWorkingDirectory)/output/*.zip'
              isPreRelease: true
              changeLogCompareToRelease: 'lastFullRelease'
              changeLogType: 'commitBased'